const books = [
    {
        id: 1,
        author: 'Stefano Benni',
        title: 'Il bar sotto il mare',
        firstPublishingYear: '1987',
        genre: ['Racconti'],
        originalLanguage: 'Italiano',
        imageName: 'ilbarsottoilmare.jpeg',
        pages: '180',
    },
    {
        id: 2,
        author: 'Stefano Benni',
        title: 'Stranalandia',
        firstPublishingYear: '1984',
        genre: ['Romanzo'],
        originalLanguage: 'Italiano',
        imageName: 'stranalandia.jpeg',
        pages: '150',
    },
    {
        id: 3,
        author: 'Haruki Murakami',
        title: 'Kafka sulla spiaggia',
        firstPublishingYear: '2002',
        genre: ['Romanzo', 'Fantastico'],
        originalLanguage: 'Giapponese',
        imageName: 'kafkasullaspiaggia.jpeg',
        pages: '566',
    },
    {
        id: 4,
        author: 'Ernest Hemingway',
        title: 'Il vecchio e il mare',
        firstPublishingYear: '1952',
        genre: ['Romanzo', 'Allegoria', 'Narrativa di mare'],
        originalLanguage: 'Inglese',
        imageName: 'ilvecchioeilmare.jpeg',
        pages: '175',
    },
    {
        id: 5,
        author: 'Robert Louis Stevenson',
        title: "L'isola del tesoro",
        firstPublishingYear: '1883',
        genre: ['Romanzo', 'Avventura'],
        originalLanguage: 'Inglese',
        imageName: 'lisoladeltesoro.jpeg',
        pages: '190',
    },
    {
        id: 6,
        author: 'Herman Melville',
        title: 'Moby Dick',
        firstPublishingYear: '1851',
        genre: ['Romanzo', 'Avventura'],
        originalLanguage: 'Inglese',
        imageName: 'mobydick.jpeg',
        pages: '422',
    },
    {
        id: 7,
        author: 'Erri De Luca',
        title: 'Il contrario di uno',
        firstPublishingYear: '2003',
        genre: ['Romanzo'],
        originalLanguage: 'Italiano',
        imageName: 'ilcontrariodiuno.jpeg',
        pages: '120',
    },
    {
        id: 8,
        author: 'Diego De Silva',
        title: 'Sono contrario alle emozioni',
        firstPublishingYear: '2011',
        genre: ['Romanzo'],
        originalLanguage: 'Italiano',
        imageName: 'sonocontrarioalleemozioni.jpeg',
        pages: '177',
    },
]